apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  # * Create namespace before use POD 
  namespace: ns-gitea
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
