apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  # * Create namespace before use this PV 
  namespace: ns-gitea
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data

