apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  # * Create namespace before use POD 
  namespace: ns-gitea
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
