apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  # * Create namespace before use this PVC
  namespace: ns-gitea
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
