apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  # * Create namespace before use Service
  namespace: ns-gitea
spec: 
  selector:
    role: nfs
  ports:
    # Remember to use opened ports
    - name: tcp-nfs
      port: 2049
      protocol: TCP

    - name: udp-nfs
      port: 111
      protocol: UDP

